// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhokttkfkchuuqqlobwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZob2t0dGtma2NodXVxcWxvYndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODk4NzUsImV4cCI6MjA2ODk2NTg3NX0.-IdSeLJb4mYpAiWImVoThKX7B20D4DcHZEx_K2wRyq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});